const MISSION_STORAGE_KEY='sjj_mission_cache_v1';
let missionSubject='commercial',missionFilter='all',missionRecords={},missionSelected=null,missionRound=1,missionLevel='circle';
function missionKey(subject,id,round){return `${subject}|${id}|${round}`;}
function missionLocalLoad(){try{missionRecords=JSON.parse(localStorage.getItem(MISSION_STORAGE_KEY)||'{}')}catch(e){missionRecords={}}}
function missionLocalSave(){localStorage.setItem(MISSION_STORAGE_KEY,JSON.stringify(missionRecords));}
function missionSubjectData(){return MISSION_DATA[missionSubject]||[];}
function missionRecord(subject,id,round){return missionRecords[missionKey(subject,id,round)]||null;}
function missionLevelsFor(problem){return [1,2,3,4,5].map(r=>missionRecord(missionSubject,problem.id,r));}
function missionStats(){const list=missionSubjectData(),records=list.flatMap(p=>missionLevelsFor(p).filter(Boolean));const first=list.filter(p=>missionRecord(missionSubject,p.id,1)).length;return{total:list.length,first,records:records.length,remaining:list.length-first,points:Number(state.missionPoints)||0};}
async function missionCloudLoad(){if(!profile?.userId)return;try{const r=await fetch(`${API_URL}?action=missionSync&userId=${encodeURIComponent(profile.userId)}&_=${Date.now()}`,{cache:'no-store'});const d=await r.json();if(!d.success)throw new Error(d.message);(d.records||[]).forEach(x=>missionRecords[missionKey(x.subject,x.problemId,x.round)]={level:x.level,points:x.points});state.missionPoints=Number(d.missionPoints)||0;missionLocalSave();save();renderAll();renderMission();}catch(e){console.warn(e)}}
function openMission(subject){missionSubject=subject;missionFilter='all';document.querySelectorAll('[data-mission-filter]').forEach(b=>b.classList.toggle('active',b.dataset.missionFilter==='all'));showScreen('mission');renderMission();missionCloudLoad();}
function renderMission(){const commercial=missionSubject==='commercial',list=missionSubjectData(),stats=missionStats();document.getElementById('missionKicker').textContent=commercial?'COMMERCIAL BOOKKEEPING':'INDUSTRIAL BOOKKEEPING';document.getElementById('missionTitle').textContent=commercial?'COM. MISSION':'IND. MISSION';document.getElementById('missionJapanese').textContent=commercial?'商業簿記':'工業簿記';document.querySelectorAll('[data-mission-switch]').forEach(b=>b.classList.toggle('active',b.dataset.missionSwitch===missionSubject));document.getElementById('missionProgressText').textContent=`${stats.first} / ${stats.total}問`;const pct=stats.total?Math.round(stats.first/stats.total*100):0;document.getElementById('missionPercent').textContent=`${pct}%`;document.getElementById('missionProgressFill').style.width=`${pct}%`;document.getElementById('missionSolvedCount').textContent=`${stats.records}回`;document.getElementById('missionPointCount').textContent=`${formatPoints(stats.points)} pt`;document.getElementById('missionRemainingCount').textContent=`${stats.remaining}問`;const chapters={};list.forEach(p=>(chapters[p.chapter]||(chapters[p.chapter]=[])).push(p));const root=document.getElementById('missionChapters');root.innerHTML='';Object.entries(chapters).forEach(([chapter,problems],idx)=>{const shown=problems.filter(p=>{const levels=missionLevelsFor(p);if(missionFilter==='unstarted')return !levels[0];if(missionFilter==='review')return levels.some(r=>r?.level==='triangle');if(missionFilter==='master')return levels.every(Boolean);return true});if(!shown.length)return;const completed=problems.filter(p=>missionRecord(missionSubject,p.id,1)).length;const d=document.createElement('details');d.className='mission-chapter';if(idx===0||missionFilter!=='all')d.open=true;d.innerHTML=`<summary><div class="mission-chapter-head"><div class="mission-chapter-name"><strong>${chapter==='補論'?'補論':`Chapter ${chapter}`}</strong><small>${completed} / ${problems.length}問${completed===problems.length?'・COMPLETE':''}</small><div class="chapter-mini-track"><div style="width:${problems.length?completed/problems.length*100:0}%"></div></div></div><span>${completed===problems.length?'MASTER':'＋'}</span></div></summary><div class="mission-problems"></div>`;const box=d.querySelector('.mission-problems');shown.forEach(p=>{const levels=missionLevelsFor(p),master=levels.every(Boolean);const row=document.createElement('button');row.type='button';row.className='mission-problem';row.innerHTML=`<span class="mission-problem-id">${p.id}</span><span class="mission-problem-title">${escapeHtml(p.title)}${master?'<small class="mission-master"> MASTER</small>':''}</span><span class="mission-rounds">${levels.map((r,i)=>`<span class="mission-round ${r?'done level-'+r.level:''}">${r?'🔥'+({triangle:'△',circle:'○',double:'◎'}[r.level]||''):(i+1)}</span>`).join('')}</span>`;row.onclick=()=>openMissionDialog(p);box.appendChild(row)});root.appendChild(d)});}
function openMissionDialog(problem){missionSelected=problem;const existing=missionLevelsFor(problem);missionRound=Math.min(5,(existing.findIndex(x=>!x)+1)||5);missionLevel='circle';document.getElementById('missionDialogSubject').textContent=missionSubject==='commercial'?'COM. MISSION':'IND. MISSION';document.getElementById('missionDialogProblem').textContent=`${problem.id}　${problem.title}`;document.getElementById('missionRoundSelector').innerHTML=[1,2,3,4,5].map(r=>`<button type="button" data-round="${r}" class="${r===missionRound?'active':''}">${r}回目${existing[r-1]?' 🔥':''}</button>`).join('');document.querySelectorAll('#missionRoundSelector button').forEach(b=>b.onclick=()=>{missionRound=Number(b.dataset.round);document.querySelectorAll('#missionRoundSelector button').forEach(x=>x.classList.toggle('active',x===b));const old=missionRecord(missionSubject,problem.id,missionRound);if(old){missionLevel=old.level;document.querySelectorAll('#missionLevelSelector button').forEach(x=>x.classList.toggle('active',x.dataset.level===missionLevel));}});document.querySelectorAll('#missionLevelSelector button').forEach(b=>b.classList.toggle('active',b.dataset.level===missionLevel));document.getElementById('missionMessage').textContent='';document.getElementById('missionDialog').showModal();}
async function saveMissionRecord(){if(!profile?.userId){toast('先に参加者登録をしてください','error');return}const btn=document.getElementById('missionSaveButton'),msg=document.getElementById('missionMessage');btn.disabled=true;msg.textContent='記録しています…';try{const d=await apiPost({action:'saveMission',userId:profile.userId,subject:missionSubject,problemId:missionSelected.id,round:String(missionRound),level:missionLevel,totalProblems:String(missionSubjectData().length)});missionRecords[missionKey(missionSubject,missionSelected.id,missionRound)]={level:missionLevel,points:Number(d.recordPoints)||0};state.missionPoints=Number(d.missionPoints)||state.missionPoints||0;missionLocalSave();save();renderAll();renderMission();document.getElementById('missionDialog').close();toast(d.alreadyExisted?'理解度を更新しました':`MISSION CLEAR! +${d.pointsAdded}pt`);}catch(e){msg.textContent=e.message}finally{btn.disabled=false}}
missionLocalLoad();document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>openMission(b.dataset.mission));document.querySelectorAll('[data-mission-switch]').forEach(b=>b.onclick=()=>{missionSubject=b.dataset.missionSwitch;renderMission();missionCloudLoad()});document.querySelector('.mission-back').onclick=()=>showScreen('home');document.querySelectorAll('[data-mission-filter]').forEach(b=>b.onclick=()=>{missionFilter=b.dataset.missionFilter;document.querySelectorAll('[data-mission-filter]').forEach(x=>x.classList.toggle('active',x===b));renderMission()});document.querySelector('.mission-dialog-close').onclick=()=>document.getElementById('missionDialog').close();document.querySelectorAll('#missionLevelSelector button').forEach(b=>b.onclick=()=>{missionLevel=b.dataset.level;document.querySelectorAll('#missionLevelSelector button').forEach(x=>x.classList.toggle('active',x===b))});document.getElementById('missionSaveButton').onclick=saveMissionRecord;
